version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      # These environment variables will override .env inside the container if set
      - CI_ENVIRONMENT=${CI_ENVIRONMENT:-production}
      - DB_HOSTNAME=db
      - DB_DATABASE=${DB_DATABASE:-nama_database}
      - DB_USERNAME=${DB_USERNAME:-username_db}
      - DB_PASSWORD=${DB_PASSWORD:-password_db}

    depends_on:
      - db
    volumes:
      # Persist writable folder
      - app_writable:/var/www/html/writable

  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password_db}
      MARIADB_DATABASE: ${DB_DATABASE:-nama_database}
      MARIADB_USER: ${DB_USERNAME:-username_db}
      MARIADB_PASSWORD: ${DB_PASSWORD:-password_db}
    volumes:
      # Persist database data
      - db_data:/var/lib/mysql

volumes:
  app_writable:
  db_data:
