version: '3.8'

networks:
  coolify:
    external: true

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - coolify
    labels:
      - "caddy_ingress_network=coolify"
      - "caddy_0.handle_path.0_reverse_proxy={{upstreams 80}}"
    environment:
      - CI_ENVIRONMENT=${CI_ENVIRONMENT:-production}
      - DB_HOSTNAME=db
      - DB_DATABASE=${DB_DATABASE:-nama_database}
      - DB_USERNAME=${DB_USERNAME:-username_db}
      - DB_PASSWORD=${DB_PASSWORD:-password_db}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_CUSTOM_ENDPOINT=${R2_CUSTOM_ENDPOINT}
      - R2_REGION=${R2_REGION}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_PUBLIC_URL=${R2_PUBLIC_URL}
      - R2_VERIFY_SSL=${R2_VERIFY_SSL}
    depends_on:
      - db
    volumes:
      - app_writable:/var/www/html/writable

  db:
    image: mariadb:10.11
    restart: unless-stopped
    networks:
      - coolify
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password_db}
      MARIADB_DATABASE: ${DB_DATABASE:-nama_database}
      MARIADB_USER: ${DB_USERNAME:-username_db}
      MARIADB_PASSWORD: ${DB_PASSWORD:-password_db}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  app_writable:
  db_data:
